name: Test Post to Bluesky

on:
  workflow_dispatch:
    
# permissions:
#   contents: read
#   id-token: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
    - name: Send Bluesky Post
      uses: myConsciousness/bluesky-post@v5
      with:
        text: |
          This is a test post!
        link-preview-url: ${{ github.server_url }}/${{repository}}
        identifier: ${{ secrets.BLUESKY_APP_USER }}  
        password: ${{ secrets.BLUESKY_APP_PASSWORD }}
        service: bsky.social    
        retry-count: 1
