name: Upload Python Package

on:
  release:
    types: [published]
    
permissions:
  contents: read
  id-token: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up Python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build .
    - name: Publish to Pypi
      uses: pypa/gh-action-pypi-publish@v1.12.2
      with:
        password: ${{ secrets.PYPI_APIKEY }}
    - name: Send Bluesky Post
      uses: myConsciousness/bluesky-post@v5
      with:
        text: |
          I've released a new version of pycmx, my module for 
          reading CMX EDLs.
        link-preview-url: ${{ github.server_url }}/${{ github.repository }}
        identifier: ${{ secrets.BLUESKY_APP_USER }}  
        password: ${{ secrets.BLUESKY_APP_PASSWORD }}
        service: bsky.social    
        retry-count: 1
