name: Upload Python Package

on:
  release:
    types: [created]
  workflow_dispatch:
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2
    - name: Set up Python
      uses: actions/setup-python@v4.6.0
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_APIKEY }}
      run: |
        python -m build .
        twine upload dist/*
    - name: Report to Mastodon
      uses: cbrgm/mastodon-github-action@v1.0.1
      with:
        message: |
          I just released a new version of pycmx, my library for reading CMX EDLs!
          #sounddesign #filmmaking #python
          ${{ github.server_url }}/${{ github.repository }}
      env:
        MASTODON_URL: ${{ secrets.MASTODON_URL }}
        MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
